services:
  app:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      # ... add more environment variables as needed
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_api
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
